import os
# pyrefly: ignore [missing-import]
from PIL import Image

def main():
    img_path = r"C:\Users\dhruv\.gemini\antigravity-ide\brain\78756275-0122-4fd4-a99a-389c33158b25\media__1780511736311.png"
    im = Image.open(img_path).convert("RGBA")
    width, height = im.size

    # Let's find a representative background color (from top right)
    bg_r, bg_g, bg_b, _ = im.getpixel((width - 10, 10))
    print(f"Detected background color: ({bg_r}, {bg_g}, {bg_b})")

    # Create a new image with transparent background
    new_data = []
    
    # We want to extract the dark text. The text is dark brown.
    # Let's calculate the distance of each pixel to the background.
    # To make it super clean, let's map pixels:
    # We can use the luminance of the text or distance from background.
    for y in range(height):
        for x in range(width):
            r, g, b, a = im.getpixel((x, y))

            # Watermark "Generated by ONEPLUS AI" is at the bottom left:
            # Let's filter out pixels in the bottom left (e.g. x < 250 and y > height - 60)
            if x < 250 and y > height - 60:
                new_data.append((0, 0, 0, 0))
                continue
                
            # The watercolor smudge is on the left (e.g. x < 350)
            # It's very light, so its distance from bg is small (dist < 40)
            # Let's check how we can handle the smudge.
            # If we only keep pixels that are significantly dark (e.g. r < 120, g < 100, b < 90),
            # that will perfectly keep only the dark brown text!
            # Let's check the text color. It's dark brown, meaning R, G, B are all quite low.
            # Let's check if the pixel matches dark brown:
            # If we use a soft threshold based on distance:
            # If dist is small (e.g., < 25), it's background.
            # If dist is large, we can calculate alpha.
            # But the watercolor smudge might have larger dist.
            # Let's see: the smudge is a very light grey/beige patch. Its red/green/blue are probably high (e.g. > 200).
            # The text is very dark (R < 100, G < 80, B < 60).
            # So if we filter by: is it dark?
            # Let's design a function to get alpha and color:
            # We want to preserve the exact dark brown color of the text (or we can enforce a clean dark brown color #3d2314).
            # Enforcing the clean brand color #3d2314 is actually BETTER because it removes all JPEG artifacts and color noise!
            # Let's check: target color is #3d2314, which is RGB(61, 35, 20).
            # Let's calculate alpha based on how "dark" the pixel is.
            # Specifically, we can use the grayscale value (luminance) of the pixel.
            # Luminance L = 0.299*R + 0.587*G + 0.114*B
            # If L is high (close to 240, which is background), alpha is 0.
            # If L is low (close to 40, which is text), alpha is 255.
            # Let's compute: alpha = clamp( (225 - L) * (255 / (225 - 40)), 0, 255 )
            # Let's try this formula!
            
            # Let's compute luminance
            l = 0.299 * r + 0.587 * g + 0.114 * b
            
            # Smudge on the left: let's see if we can suppress it by applying a stricter threshold for x < 380
            # Or if we just use a threshold: only pixels with l < 180 can have alpha > 0.
            # In the smudge, is l < 180? Probably not, since the smudge is very faint.
            # Let's verify by writing a script that prints pixel info for different regions.
            
            # Let's check a threshold:
            max_l = 210  # anything lighter than this is fully transparent
            min_l = 60   # anything darker than this is fully opaque
            
            if l >= max_l:
                alpha = 0
            elif l <= min_l:
                alpha = 255
            else:
                alpha = int(255 * (max_l - l) / (max_l - min_l))
                
            # If x is on the left (x < 370) and it's not very dark, it's probably the smudge.
            # Let's check if we can make the smudge region clean.
            # The script text starts around x = 300.
            # Let's print the bounding box of dark pixels (l < 150) to see where the text actually is.
            
            # For the output pixel, let's keep the original color, but set the new alpha.
            # Actually, to make it look extremely premium and clean, we can force the text color to be
            # a smooth blend of the brand color (61, 35, 20) based on alpha!
            # This avoids any background color bleeding into the edges of the text (halo effect).
            # Brand color: (61, 35, 20)
            new_data.append((61, 35, 20, alpha))

    new_im = Image.new("RGBA", im.size)
    new_im.putdata(new_data)
    
    # Now let's crop the image to the actual text bounding box.
    # The bounding box of the non-transparent pixels:
    bbox = new_im.getbbox()
    print("Bounding box before left-smudge filter:", bbox)
    
    # Let's refine the bounding box to exclude the smudge on the left and watermark.
    # The script text starts around x=300 (or we can find it programmatically).
    # Let's inspect the bounding box of pixels with alpha > 50 and x > 300.
    left, top, right, bottom = width, height, 0, 0
    for y in range(height):
        for x in range(width):
            # Exclude watermark and smudge:
            # Watermark is at y > height - 60 and x < 250.
            # Smudge is at x < 350. Let's see: does the 'K' of Keshvi start before x=350?
            # Let's check! The image is 1024 wide. "Keshvi" is centered/right, "CRAFTS" is centered/right.
            # Let's find the first column from the left that has high density of dark pixels,
            # or just look at the bounding box of pixels with alpha > 100.
            _, _, _, alpha = new_im.getpixel((x, y))
            if alpha > 50:
                # If it's the smudge (x < 330 and alpha is low/moderate), skip it
                if x < 320 and alpha < 200:
                    continue
                # If it's the watermark (x < 250 and y > 400), skip it
                if x < 250 and y > height - 80:
                    continue
                if x < left: left = x
                if x > right: right = x
                if y < top: top = y
                if y > bottom: bottom = y
                
    print(f"Refined Bounding Box: ({left}, {top}, {right}, {bottom})")
    
    # Let's crop to this refined bounding box plus some padding (e.g. 10px)
    padding = 10
    crop_left = max(0, left - padding)
    crop_top = max(0, top - padding)
    crop_right = min(width, right + padding)
    crop_bottom = min(height, bottom + padding)
    
    cropped_im = new_im.crop((crop_left, crop_top, crop_right, crop_bottom))
    
    # Save the cropped transparent image
    os.makedirs("public/uploads/hero", exist_ok=True)
    cropped_im.save("public/uploads/hero/logo_new.png", "PNG")
    print("Saved logo_new.png")

if __name__ == "__main__":
    main()
